management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    hostname: localhost
    preferIpAddress: 'true'
  client:
    fetchRegistry: 'false'
    registerWithEureka: 'false'
spring:
  config:
    name: eureka
  application:
    name: api-registry-server
  boot:
    admin:
      client:
        url: =http://192.168.0.11:8082
server:
  port: '8761'

